
module.exports = {
    INVALID_FORM_VALIDATION:"Invalid entry, please check the error & try again.",
    DAO_EMAIL_ERROR_COM:"You cannot sign up from @daoproptech.com address, please use a different email.",
    DAO_EMAIL_ERROR_ORG:"You cannot sign up from @daocapital.org address, please use a different email.",
    DUPLICATE_EMAIL:"This email address is associated with another account, please try signing in.",
    ERROR_OCCURRED:"An error occurred",
    ERROR_EMAIL_VERIFICATION:"Couldn't verify email. Please try again.",
    INCORRECT_EMAIL_PASS:"Incorrect email address or password, please try again.",
    INCORRECT_MOBILE_PASS:"Incorrect mobile number or password, please try again",
    ACC_NOT_APPROVED: "Account is not approved from admin.",
    ACC_NOT_VERIFIED:"Account wasn't verified, please try again.",
    ERROR_USER_SIGIN_IN:"Couldn't sign in, please try again.",
    TRY_AGAIN:"Please try again later.",
    TOKEN_EXPIRED:"The token is expired or invalid, please try again.",
    ERROR_PASS_RESET:"Couldn't reset your password, please try again.",
    ERROR_PASS_CHANGE:"Couldn't change your password, please try again.",
    ERROR_PASS_CHANGE_REQUEST: "Incorrect email address / account not found. Please try again.",
    CURRENT_PASS_INCORRECT:"You have entered an incorrect password. Please try again.",
    USER_NOT_FOUND:"User not found, please ensure you're using the correct credentials.",
    ERROR_OCCURRED_INOPERATION:"An error occurred",
    CONFIG_NOT_ENABLED:"Configuration not enabled, please contact Customer Support or reset your password.",
    EMAIL_VERIFIED:"Email address has been verified.",
    USER_HAVE_LOGGED_IN:"User logged in successfully.",
    REQ_SENT_TO_EMAIL:"Request sent to your email address.",
    PASS_CHANGED:"Your password has been changed, please log in with your new password.",
    PASS_CHANG_ENABLE:"Password change enable for user",
    PASS_UPDATED:"Password updated.",
    ERR0R_PASS_UPDATED:"Couldn't update password, please try again.",
    OPT_INVALID:"Invalid OTP, please try again.",
    USER_VERIFIED:"User verified.",
    ERROR_PHONE_VERIFICATION:"Couldn't verify phone number, please try again.",
    ERROR_REVOKING_SESSION:"Couldn't revoke session, please try again.",
    LOGOUT_SUCCESS:"You've logged out successfully.",
    UNABLE_FETCH_GOAL:"Unable to fetch goals, please refresh or try again.",
    GOAL_ADDED_SUCCESSFUL:"Goal added successfully.",
    UNABLE_SAVE_INFO:"Couldn't save your information, please try again.",
    UNABLE_FETCH_BUSSI_INFO:"Unable to fetch business information, please try again.",
    COMPLETE_PROFILE_SETUP:"Profile setup complete.",
    PHONE_NO_INUSE:"The phone number is already being used, please enter a different number.",
    VERIFY_YOUR_PHONENO:"Please verify your phone number.",
    USER_COMPLETE_PROFILE_SETUP:"Profile setup complete.",
    USER_INFO_UPDATED:"User information updated.",
    ERROR_UPDATING_USER:"Couldn’t update user information, please try again.",
    ERROR_SIGNUP_COM:"You cannot sign up from @daoproptech.com address, please use a different email.",
    ERROR_SIGNUP_ORG:"You cannot sign up from @daocapital.org address, please use a different email.",
    EMAIL_ASSOCIATED_OTHER_ACCOUNT:"This email address is assocaited with another account, please try signing in.",
    EMAIL_DUPLICATE_ERROR:"Please enter a different email address.",
    EMAIL_ADDRESS_UPDATED:"Email address has been updated.",
    ERROR_UPDATING_EMAIL:"Couldn't update email address, please try again.",
    ERROR_UPDATING_PHONE:"Couldn’t update phone number, please try again.",
    USER_PHONE_UPDATED:"Your phone number has been updated.",
    ERROR_FETCH_USER_DETAIL:"Couldn't fetch your details, please refresh or try again.",
    ERROR_FETCH_USER_INFO:"Couldn’t fetch your information, please refresh or try again.",
    USER_INFO_UPDATED_SUCCESS:"Your information has been updated successfully.",
    ERROR_UPDATEING_INFO:"Couldn’t update information, please try again.",
    EMAIL_CONFIRMATION_SEND:"Email confirmation messsage sent.",
    ERROR_SENDING_EMAIL:"Email wasn't sent, please try again.",
    USER_ACCO_VIA_EMAIL:"Account created via email address.",
    PASS_CHANGE_BY_ADMIN_USERID:"Admin changed the password for this user.",
    CNIC_UPDATE_SUCCESS:"ID number updated successfully.",
    BILLING_INFO_UPDATE_SUCCESS:"Billing information updated successfully.",
    PASS_CONFIG_NOT_ENABLED:"Password configuation is not enabled.",
    PROFILE_UPDATED:"Profile updated sucessfully.",
    USER_NEXTOFKIN_INFO_UPDATED_SUCCESS:"Next of Kin information updated successfully",
    ACCOUNT_SUSPENDED: "Account have been suspended",
    ACCOUNT_APPROVED: "Account have been approved",
    ERROR_OCCURRED_IN_ACCOUNT_SUSPENSION: "Error occurred in suspending account",
    ERROR_OCCURRED_in_ACCOUNT_APPROVAL: "Error occurred in approving account",
    ACCOUNT_SUSPENDED_CLIENT_MESSAGE: "Your account have been suspend. Please contact support to reactivate your account",
    ACCOUNT_ACTIVATION: "Account have been activated",
    ERROR_OCCURRED_IN_ACCOUNT_ACTIVATION: "Error occurred in account activation",
    BANK_ACCOUNT_SAVED: "Bank Account has been saved",
    BANK_ACCOUNT_DELETED: "Bank Account deleted",
    SPAM_ERROR_ALERT: "Error verifying reCAPTCHA, please try again."
}